---
title: "Assignment 8 (3)"
author: "33140 (Sahil Naphade)"
date: "16/04/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Reading the Iris dataset file and giving the header names
Plot the scatter graph of petal length
```{r}
wd = getwd()
setwd(wd)

iris=read.csv("../../Sl-VI DataSets/Iris/Iris.csv",header = F, sep = ',')
head(iris)

names(iris) <- c('Sepal.Length',"Sepal.Width","Petal.Length","Petal.Width","Class")

plot(iris$Petal.Length)

```

Plot bar graph of numbr of records vs. class

```{r}
#BAR CHARTS

barplot(c(30,46,14),ylab = c("setosa","versicolor","virginica"), main = "species quantity" )
```


```{r}
barplot(c(30,46,14), main = "species quantity",names.arg = c("setosa","versicolor","virginica") )

```

Sepal length bar graph
```{r}
barplot(iris$Sepal.Length, main = "sepal length of iris" )


```

Sepal length histogram
```{r}
hist(iris$Sepal.Length,main = "sepal length of iris",col="darkmagenta",freq=FALSE)
```

Pie chart of total records
```{r}
#PIE CHART
x<-c(25,30,45)
label<-c("setosa","versicolor","virginica")
radius<-40
color<-c("orange","brown","pink")
pie(x,label,40,main = "Specis of iris flower",col = color,clockwise = FALSE)

```
Printing summary
```{r}
y<-c(summary(iris$Species))
color<-c("orange","blue","pink")

```

```{r}

#scatterplot
plot(iris$Petal.Length,iris$Petal.Width,main = "Iris Petals Analysis",xlab = "Length",ylab = "Width",xlim = c(0,8),ylim = c(0,2.5),axes = TRUE,col=1)
```

