---
title: "Assignment5_A"
author: "33140 (Sahil Naphade)"
date: "23/04/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Read the data 
```{r}
# Roll no. 33140
# Batch L9
# Assignment 5 (1) : Perform subsetting, melting and casting of dataset (Facebook).

setwd("G:/College/SL6/Assignment5/")

dataset_Facebook = read.csv2("G:/College/Sl-VI DataSets/dataset_Facebook.csv",header = T, sep = ';')
str(dataset_Facebook)
```
Subset the data
```{r}

#subsetting as per photos
v1 <- subset(dataset_Facebook,type = "photo")
# View(v1)
str(v1)
```

```{r}
# subsetting as per videos
v2 <- subset(dataset_Facebook,type = "video")
# View(v2)
str(v2)
```
Merging data
```{r}
#merge data
m1 <- merge(v1,v2,by="Paid")
# View(m1)
str(m1)
```

Sort as per comments
```{r}
#sort data
s1 <- dataset_Facebook[order(dataset_Facebook$comment),]
# View(s1)
str(s1)
```

```{r}
#sorting data in ascending order as number of comments, and then decreasing number of shares
s2 <- dataset_Facebook[order(dataset_Facebook$comment, -dataset_Facebook$share),]
# View(s2)
str(s2)
```

```{r}
# Transposing Data (Row names bacome column names)
t(v1)
```
Melting the data

```{r}
# Melting Data to long format
library(reshape2)
# Melt, i.e. each row is a unique ID-variable combination
m1 <- melt(v2, id <-  c("Type","Lifetime.Post.Total.Reach"))
m2 <- m1 # Extra variable
View(m1)
# head(m1)
# tail(m1)
str(m1)
```

Clean
```{r}
levels(m1$variable)[levels(m1$variable) == 'Paid'] <- 'first'
levels(m1$variable)[levels(m1$variable) == 'Lifetime.Post.Total.Impressions'] <- 'second'
m1

# Sort as per Type and variable
# This is long format
m1 <- m1[ order(m1$Type,m1$variable),]
m1

```

```{r}
# Long to wide
m2_wide = dcast(m2,Type + Lifetime.Post.Total.Reach ~ variable, value.var = "value")
  # This is the wide format data
str(m2_wide)
```

